project_id = "jrklkknipbhnmjihldsh"

[functions.split-chapter]
verify_jwt = false

[functions.track-progress] 
verify_jwt = false

[functions.get-reader-feed]
verify_jwt = false

[functions.get-writer-analytics]
verify_jwt = false

[functions.admin-moderate]
verify_jwt = false

[functions.manage-ads]
verify_jwt = false

[functions.get-slides-with-ads]
verify_jwt = false